### ISSUE TITLE
Feb 25 Backlog

### ISSUE THREAD

**Issue by matthewhanson** [AmericanRedCross/osm-stats#19]
Backlog for OSM Stats

Affected Repositories:  osm-stats, planet-stream, osm-stats-worker, osm-stats-api, osm-stats-users, osm-stats-leaderboard
- [x] Update/add license on all repos to be BSD-3
- [x] Documentation (badges, api endpoints, flow of information, CONTRIBUTING.md)
- [x] move develop branches over to master on all repos
- [x] update travis on osm-stats-workers to create packaged zip of master rather than develop branch
- [x] move migrations for database from osm-stats-workers (and duplicated in osm-stats-api) to osm-stats under deploy/db
- [x] fix logging on Red Cross EC2 ( @dalekunce to get us key and url to login )
- [x] add monitored hashtags to an environment variable

@kamicut @smit1678 @nbumbarger @DylanMoriarty @laurencjay

**Comment by dalekunce** [comment]
License is actually BSD-3 clause now.

**Comment by kamicut** [comment]
@dalekunce So should we move all osm-stats-\* repos to BSD-3?

**Comment by dalekunce** [comment]
I did most of them already I think. But yes, all the stuff we did and will do is now BSD 3 clause.

**Comment by kamicut** [comment]
Great we'll make sure to update the `package.json` files and not overwrite those LICENSE files when merging.

**Comment by dalekunce** [comment]
:+1:

**Comment by smit1678** [comment]
To close this out: 
- api docs are here: https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/API.md
- badge docs are here: https://github.com/AmericanRedCross/osm-stats/blob/master/documentation/Adding_Badges.md
