### ISSUE TITLE
allow worker to skip past a failing changeset after a number of tries

### ISSUE THREAD

**Issue by kriscarle** [AmericanRedCross/osm-stats#35]
If the Lambda worker errors on a changeset more than X times, make a record of what failed then remove it from Kinesis so processing can move forward. Since Lambda is stateless, this will require using Redis or Postgres.

My instance is stuck on a changeset that encounters a bug in one of the metric calculations. The problem is Lambda just keeps pulling and retrying that same changeset over and over.

**Comment by matthewhanson** [comment]
osm-stats-workers was updated a while ago to always return a success and log the failure.
