### ISSUE TITLE
corrupt contribution timeline when editing Missing Maps

### ISSUE THREAD

**Issue by Martinairmaps** [AmericanRedCross/osm-stats#40]
When editing in Missing Maps, this is _frequently_ NOT noted in the Contributions Timeline.
The HOTOSM Tasking Manager, however, does note that these edits were made! 
This happens e.g. in the Malawi project #2381. See the following examples:
- http://www.missingmaps.org/users/#/3376734

- ![screenprint 2381 task 282 2017-02-20 om 18 07 33](https://cloud.githubusercontent.com/assets/25906567/23135198/eee0a162-f797-11e6-9039-8cbced7eff81.jpg)
The edits Contribution Timeline seems to be corrupt (at times). What goes wrong?
 Please do something about this (it has been mentioned before)!

**Comment by dalekunce** [comment]
Looks like you editing when the system had a hiccup. We are working to resolve it now.
