### ISSUE TITLE
Mismatch between /hashtags/tag and /users/123

### ISSUE THREAD

**Issue by bjohas** [AmericanRedCross/osm-stats#44]
The API is excellent! I'm trying to make sense of some discrepancies.

E.g. there seems to be a discrepancy between 
http://osmstats.redcross.org/hashtags/mmcambridge/users
and
http://osmstats.redcross.org/users/6172975
?

How often does the API data refresh?

Thanks!

**Comment by dalekunce** [comment]
Data is _always_ refreshing. those discrepancies are most likely because of some issues we've had with the Overpass API and data replication.

**Comment by bjohas** [comment]
Thanks for the response! Do you mean transient issues or ongoing issues?

**Comment by kamicut** [comment]
@bjohas data is replicated minutely as soon as we can get it from planet.osm and the Augmented Diff API in Overpass. If we experience lag in replication, the changesets can drop. We do not currently have a method to historically backfill derived spatial statistics (length of road changed by a user at a certain time takes a long time to resolve in Overpass) but we're looking into ways to backfill tag-based statistics.

**Comment by bjohas** [comment]
@kamicut Ok, so you only replicate data that has a missingmaps hashtag? Or you get all data but augment it with hashtags where available? Thanks!

**Comment by dalekunce** [comment]
@bjohas we track all data with any hashtag. However, for stats only those edits with #missingmaps are counted for MM stats.

**Comment by bjohas** [comment]
@dalekunce Sorry, trying to understand :) So you have a complete copy of the OSM planet?  Or only where the character '#' appears in changeset comments? Thanks!

**Comment by dalekunce** [comment]
@bjohas only when a '#' in in the changeset comment.

**Comment by bjohas** [comment]
OK, thanks!!
