### ISSUE TITLE
Extending the API [feature request]

### ISSUE THREAD

**Issue by bjohas** [AmericanRedCross/osm-stats#45]
Hello,

is there interest in extending the API? We've got some ideas for creating a JOSM plugin, that can use the osm-stats API results for validating during mapathons. We could build this separately (calling the API when needed), but it could also be integrated into the API if there's interest.

Thanks!

**Comment by dalekunce** [comment]
@bjohas Happy to review and approve any PRs that you send. I like the idea of using it for validation.

**Comment by bjohas** [comment]
@dalekunce Thanks! I've posted something on the HOT mailing list, to see what interest there is among validators. Let's see what comes back. Would you be happy to have a chat, to see whether what we propose is reasonable?

**Comment by dalekunce** [comment]
super happy to work through ideas. I suggest putting them all here and that then we can prioritize them. @bjohas

**Comment by bjohas** [comment]
@dalekunce I experimented with some code here (nodejs):
https://github.com/OSM-Utilities/JOSM-Scripts-HOT/blob/master/lib/mmstats.js
There's comments that explain how it works.

Also see comment here: https://github.com/AmericanRedCross/osm-stats/issues/44 - the above script uses the hashtag to get users from osmstats, which works for most projects straight off the tasks server, which make it hard to not add the hashtag. However, for stats from a local mapathon (e.g. adding mmcambridge manually) is hit and miss, in which case it's useful to be able to look through the full planet data in an area.
