### ISSUE TITLE
Enable https on deployed site

### ISSUE THREAD

**Issue by bjohas** [AmericanRedCross/osm-stats#47]
Hello,

we're turning our stats app into a webapp (see https://github.com/OSM-Utilities/JOSM-Scripts-HOT/blob/master/lib/mmstats.js). Could you enable https on your server, so that e.g.
https://osmstats.redcross.org/hashtags/mmcambridge/users
works?

Many thanks!

**Comment by dalekunce** [comment]
Sure I think we can help you out with that. cc @danbjoseph

**Comment by bjohas** [comment]
That's great, many thanks!

**Comment by bjohas** [comment]
Hello! Just wondering how this is going? We've got a mapathon on Thursday, and it would be great to have https in place.... Many thanks!

**Comment by danbjoseph** [comment]
We're waiting on IT for part of it. The request has been approved, just not done. I've pinged them to ask for an update. Will let you know when I hear something. Thanks for your patience.

**Comment by bjohas** [comment]
OK, that's great - looking forward to it!

**Comment by bjohas** [comment]
Hello - we've got a webinar tomorrow, where we'll demo our tool. It would be very neat if we could demo the tool "online" (i.e. requiring https) rather than running off a local file. Any updates?! Thanks :)

**Comment by danbjoseph** [comment]
rollout of the https, what with the docker image and some other stuff, is proving more complex than we initially realized and we're looping in the developers who worked on the project. unfortunately, doesn't look like it'll be ready by tomorrow. but hopefully soon. thanks for your patience and understanding.

**Comment by danbjoseph** [comment]
@kamicut helped us out. @bjohas it should be up and running now.

**Comment by bjohas** [comment]
Amazing - thank you!
