### ISSUE TITLE
josm_edits.js missing from project

### ISSUE THREAD

**Issue by openbrian** [AmericanRedCross/osm-stats#49]
It's used in the josm migration script.  It appears to still be part of osm-stats-workers.

**Comment by dalekunce** [comment]
@openbrian what are you referring too exactly. can you write out more what the issue is, more than just a missing file.

**Comment by rgwozdz** [comment]
Same issue here.  The reason is because the `metrics/josm_edits.js` actually exists in a different repo. See [https://github.com/AmericanRedCross/osm-stats-workers/tree/master/src/metrics](https://github.com/AmericanRedCross/osm-stats-workers/tree/master/src/metrics).

**Comment by sethfitz** [comment]
This refers to the previous version of osm-stats-workers and is no longer relevant.
