### ISSUE TITLE
Is the architecture diagram still an accurate depiction?

### ISSUE THREAD

**Issue by rgwozdz** [AmericanRedCross/osm-stats#51]
Hello  -
I've been looking at the recent commits to this repo as well as osm-stats-workers and osm-stats-api.  Curious if the diagram on the deploy readme [page](https://github.com/AmericanRedCross/osm-stats/tree/master/deploy) is still an accurate description of the deployed ecosystem...?  There were several changes committed to osm-stats-workers last week, in particular, and it seems that example code for connecting osm-stats-workers to kinesis and event-hubs was removed.  Can you confirm that kinesis (or event hub) is still a required part of the osm-stats stack?

**Comment by sethfitz** [comment]
No, it's no longer accurate. I'm in the process of rolling out changes, so I haven't gotten around to updating docs and whatnot.

Kinesis is no longer required; `bin/osm-changes.js` in osm-stats-workers is now a standalone tool for replicating OSM data from changeset diffs + augmented diffs.

**Comment by rgwozdz** [comment]
Thanks for the quick reply.  Does that mean that planet-stream is also no longer a required component?

**Comment by sethfitz** [comment]
Correct. https://github.com/mojodna/osm-replication-streams replaces it.
