### ISSUE TITLE
Are knex and db/migrations still the way to set up database?

### ISSUE THREAD

**Issue by rgwozdz** [AmericanRedCross/osm-stats#52]
One of the original deployment [scripts](https://github.com/AmericanRedCross/osm-stats/blob/2c1985544196e3dc9478c527119bf454fb08c43e/deploy/osmstats.py#L31-L44) for osm-stats notes the use of `knex` and `db/migrations` and `db/seeds` [files](https://github.com/AmericanRedCross/osm-stats/tree/master/db) for setting up the datastore.  Is this still the prescribed way of doing this?  I notice that osm-stats-workers has its own set of `.sql` files but it's not clear to me how they are used or if they supersede the `db/migrations` files.

**Comment by sethfitz** [comment]
The `.sql` files supersede knex migrations; run `make db/all` w/ `DATABASE_URL` set from osm-stats-workers to initialize the db.
